### ISSUE TITLE
npm run generate:random-data throwing error in angular 9

### ISSUE THREAD

**Issue by jayeshagwan1** [andrewthauer/ng-inventory-app#15]
Hi @andrewthauer . when I run npm run generate:random-data I am getting error : 
![image](https://user-images.githubusercontent.com/616970/97294407-f3788680-1873-11eb-9811-1f7e6a79a4e7.png)

**Comment by andrewthauer** [comment]
@jayeshagwan1 - I haven't touched this project is ages, so I'm not exactly sure. However, from the error alone it might be a bug in the npm script. You could try running `ts-node ./randon-data` and see what happens.
